spring:
  jpa:
    hibernate:
       ddl-auto: update
    properties:
      hibernate:
        default_schema:  
        dialect: org.hibernate.dialect.MySQLInnoDBDialect
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQLInnoDBDialect                      
  datasource:
    url: jdbc:mysql://localhost:3306/gtfsdb?useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: MyNewPass

#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE
              
#application properties setup
app:
  message_api_url: https://coll-aru-24sender.app24pa.it/rest/
  operator_username: damiano
  operator_password: Damiano123
  sender_id: 2
  
#https://coll-extapi.whereapp.it/

#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show-sql=true
#spring.datasource.url=jdbc:postgresql://172.16.0.113:5432/itwa
#spring.datasource.username=postgres
#spring.datasource.password=@vjtech@
#spring.jpa.properties.hibernate.default_schema=schematest


#spring.datasource.initialization-mode=always
#spring.datasource.initialize=true
#spring.datasource.schema=classpath:/schema.sql
#spring.datasource.continue-on-error=true

#application properties setup
#app.message_api_url = https://coll-extapi.whereapp.it/

#spring.devtools.livereload.enabled=true
#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=jdbc:mysql://localhost:3306/gtfsdb?useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
#spring.datasource.username=root
#spring.datasource.password=MyNewPass
#spring.jpa.show-sql=false
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLInnoDBDialect
#server.port=3306

