#spring.devtools.livereload.enabled=true
#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=jdbc:mysql://localhost:3306/gtfsdb?useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
#spring.datasource.username=root
#spring.datasource.password=MyNewPass
#spring.jpa.show-sql=false
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLInnoDBDialect
#server.port=3306

app:
  message_api_url: https://coll-aru-24sender.app24pa.it/rest/ 